[package]
name = "compiler-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
compiler-lexer = { path = "../compiler-lexer" }
ecow = "0.2.6"

[dev-dependencies]
pretty_assertions = "1"
