[package]
name = "compiler-lexer"
version = "0.1.0"
edition = "2024"

[dependencies]
bstr = "1.12.1"
ecow = "0.2.6"
itertools = "0.14.0"
miette = "7.6.0"
thiserror = "2.0.17"

[dev-dependencies]
pretty_assertions = "1"
